version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - /tmp/mtrial/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/mtrial
      - /tmp/mtrial/mysqld:/run/mysqld
    depends_on:
      - db
