# Generated by Django 4.0 on 2022-06-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctgov1',
            fields=[
                ('nct_id', models.CharField(db_column='nct_id', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('id_out', models.IntegerField(blank=True, null=True)),
                ('drank_out', models.IntegerField(blank=True, db_column='Drank_out', null=True)),
                ('id_desc', models.IntegerField(blank=True, null=True)),
                ('drank_desc', models.IntegerField(blank=True, db_column='Drank_desc', null=True)),
                ('drank_final', models.IntegerField(blank=True, db_column='Drank_final', null=True, verbose_name='Ranking')),
                ('brief_title', models.TextField(blank=True, null=True)),
                ('official_title', models.TextField(blank=True, null=True)),
                ('overall_status', models.TextField(blank=True, max_length=48, null=True)),
                ('phase', models.TextField(blank=True, max_length=12, null=True)),
                ('enrollment', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=68)),
                ('updated', models.DateField(blank=True, null=True)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('new', models.CharField(max_length=1)),
                ('emailab', models.IntegerField(db_column='emailAB')),
                ('action', models.CharField(blank=True, max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alloc', models.ForeignKey(db_column='Alloc', on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Allocated to')),
            ],
            options={
                'verbose_name': 'Trials',
                'verbose_name_plural': 'Trials',
                'db_table': 'CTgov1_bk',
                'ordering': ['-drank_final'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=36, null=True)),
                ('phone', models.CharField(max_length=36, null=True)),
                ('email', models.CharField(max_length=36, null=True)),
                ('nct_id', models.ForeignKey(db_column='nct_id', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='trials.ctgov1')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
                'db_table': 'CTgovContacts',
                'ordering': ['-nct_id'],
                'managed': True,
            },
        ),
    ]
